make clean
make all

RINGMASTER_HOSTNAME=127.0.0.1
RINGMASTER_PORT=9001
NUM_PLAYERS=5
NUM_HOPS=100

./ringmaster $RINGMASTER_PORT $NUM_PLAYERS $NUM_HOPS &

sleep 2

for (( i=0; i<$NUM_PLAYERS; i++ ))
do
    ./player $RINGMASTER_HOSTNAME $RINGMASTER_PORT &
done

wait
