CFLAGS=-std=gnu99 -ggdb3
PROGS=ringmaster player
all: $(PROGS)
ringmaster: ringmaster.o functions.o
 gcc -o $@ $^
player: player.o functions.o
 gcc -o $@ $^
%.o: %.c
 gcc $(CFLAGS) -c $<
ringmaster.o:functions.h potato.h
player.o:functions.h potato.h
clean:
 rm -f $(PROGS)